-- Script para crear la tabla de registro de check-in diario (Staff) en Supabase

CREATE TABLE checkins_diarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repartidor_id TEXT NOT NULL,
    fecha DATE NOT NULL,
    hora_primer_mensaje TIME NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Restricción clave: Solo un check-in por repartidor por día.
-- Esto permite hacer ON CONFLICT DO NOTHING (o capturar la excepción silenciosamente)
ALTER TABLE checkins_diarios ADD CONSTRAINT checkins_unicos_por_dia UNIQUE (repartidor_id, fecha);

-- Habilitar RLS (Row Level Security) - Opcional pero recomendado en Supabase
ALTER TABLE checkins_diarios ENABLE ROW LEVEL SECURITY;

-- Política para permitir inserción y lectura anónima (Asumiendo que el server usa la anon key o service role)
CREATE POLICY "Permitir todo a anon" ON checkins_diarios FOR ALL USING (true) WITH CHECK (true);
